### ISSUE TITLE
There is something wrong with the CyRK==0.10.1 wheel for py310 on win_amd64 from PyPI

### ISSUE THREAD

**Issue by dihm** [jrenaud90/CyRK#62]
If you try to install the `CyRK-0.10.1-cp310-cp310-win_amd64.whl` wheel from PyPI (using pip) you get the following error:

```shell
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\commands\install.py", line 457, in run
    installed = install_given_reqs(
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\req\__init__.py", line 70, in install_given_reqs
    requirement.install(
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\req\req_install.py", line 867, in install
    install_wheel(
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 732, in install_wheel
    _install_wheel(
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 590, in _install_wheel
    file.save()
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\site-packages\pip\_internal\operations\install\wheel.py", line 380, in save
    shutil.copyfileobj(f, dest, blocksize)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\zipfile.py", line 930, in read
    data = self._read1(n)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\zipfile.py", line 1020, in _read1
    self._update_crc(data)
  File "C:\Users\naqsL\miniconda3\envs\py310\lib\zipfile.py", line 948, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'CyRK/array/interp.cp310-win_amd64.pyd'
```

It appears there is some checksum-like issue with the compression in the wheel.

**Comment by jrenaud90** [comment]
Thanks for the report @dihm. I can reproduce this, working on a fix. In the mean time it looks like it works for me if you do `pip install CyRK --no-binary CyRK` this will install it from source code.

**Comment by jrenaud90** [comment]
Okay things look to be working with v0.10.2 (PR #64). Let me know if it is still a problem for you!
